### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by expirience** [lekesako/MMM-Pollen-FR#2]
Hello, I can't install the module on my environment.

I downloaded the module in the modules directory and when I run the "npm install" command I have the return below

```
node@29e7a3a92121:/opt/magic_mirror/modules/MMM-Pollen-FR$ npm install

> magicmirror@2.21.0 postinstall
> npm run install-vendor && npm run install-fonts && echo "MagicMirror² installation finished successfully!
> "


> magicmirror@2.21.0 install-vendor
> echo "Installing vendor files ...
> " && cd vendor && npm install --loglevel=error --no-audit --no-fund --no-update-notifier

Installing vendor files ...


up to date in 152ms

> magicmirror@2.21.0 install-fonts
> echo "Installing fonts ...
> " && cd fonts && npm install --loglevel=error --no-audit --no-fund --no-update-notifier

Installing fonts ...


up to date in 133ms
MagicMirror² installation finished successfully!


> magicmirror@2.21.0 prepare
> [ -f node_modules/.bin/husky ] && husky install || echo no husky installed.

no husky installed.

up to date, audited 287 packages in 5s

41 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (3 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
I'm using MagicMirror on a docker environment (following the documentation (https://khassel.gitlab.io/magicmirror/installation/))

Can you help me ?

**Comment by expirience** [comment]
Error after restart service : 

```
[22.11.2022 17:49.39.886] [ERROR] Error: Cannot find module 'request'
Require stack:
- /opt/magic_mirror/modules/MMM-Pollen-FR/node_helper.js
- /opt/magic_mirror/js/app.js
- /opt/magic_mirror/serveronly/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-Pollen-FR/node_helper.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/magic_mirror/modules/MMM-Pollen-FR/node_helper.js',
    '/opt/magic_mirror/js/app.js',
    '/opt/magic_mirror/serveronly/index.js'
  ]
}

```
